services:
  kali:
    image: sinfallas/kali-linux-headless:latest
    container_name: kali
    hostname: kali
    restart: unless-stopped
    pull_policy: always
    tty: true
    privileged: true
    network_mode: host

  postgres:
    image: postgres:17.6
    hostname: postgres
    container_name: postgres
    pull_policy: always
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=s2dE7uCADCK1zJCfHODicc6oLaLjBdsq #change me
      - POSTGRES_DB=kali
      - TZ=America/Caracas
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U user -d kali']
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
